parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64
  default: amd64

- name: pool
  type: string
  values:
  - sonicbld
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string

- name: debian_version
  type: string

- name: sairedis_artifact_name
  type: string

- name: swss_common_artifact_name
  type: string

- name: artifact_name
  type: string

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    ${{ if ne(parameters.pool, 'default') }}:
      name: ${{ parameters.pool }}
    ${{ else }}:
      vmImage: 'ubuntu-20.04'

  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}

  steps:
  - checkout: sonic-swss
    submodules: true
    clean: true
  - script: |
      set -ex
      git checkout $(BUILD_BRANCH)
      git submodule update
      git status
    displayName: Set up sonic-swss branch
  - script: |
      sudo apt-get update
      sudo apt-get install -y \
        libhiredis-dev \
        libzmq3-dev \
        swig4.0 \
        libdbus-1-dev \
        libteam-dev
    displayName: "Install dependencies"
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: ${{ parameters.swss_common_artifact_name }}
      path: $(Build.ArtifactStagingDirectory)/download
      patterns: |
        libswsscommon_1.0.0_*.deb
        libswsscommon-dev_1.0.0*.deb
    displayName: "Download pre-stage built ${{ parameters.swss_common_artifact_name }}"
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: ${{ parameters.sairedis_artifact_name }}
      path: $(Build.ArtifactStagingDirectory)/download
      patterns: |
        libsaivs_*.deb
        libsaivs-dev_*.deb
        libsairedis_*.deb
        libsairedis-dev_*.deb
        libsaimetadata_*.deb
        libsaimetadata-dev_*.deb
        syncd-vs_*.deb
    displayName: "Download pre-stage built ${{ parameters.sairedis_artifact_name }}"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: Azure.sonic-buildimage.common_libs
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/$(BUILD_BRANCH)'
      path: $(Build.ArtifactStagingDirectory)/download
      artifact: common-lib
      patterns: |
        target/debs/${{ parameters.debian_version }}/libnl-3-200_*.deb
        target/debs/${{ parameters.debian_version }}/libnl-3-dev_*.deb
        target/debs/${{ parameters.debian_version }}/libnl-genl-3-200_*.deb
        target/debs/${{ parameters.debian_version }}/libnl-genl-3-dev_*.deb
        target/debs/${{ parameters.debian_version }}/libnl-route-3-200_*.deb
        target/debs/${{ parameters.debian_version }}/libnl-route-3-dev_*.deb
        target/debs/${{ parameters.debian_version }}/libnl-nf-3-200_*.deb
        target/debs/${{ parameters.debian_version }}/libnl-nf-3-dev_*.deb
        target/debs/${{ parameters.debian_version }}/libyang_*.deb
    displayName: "Download common libs"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: sonic-net.sonic-dash-api
      ${{ if eq(parameters.arch, 'amd64') }}:
        artifact: sonic-dash-api
      ${{ else }}:
        artifact: sonic-dash-api.${{ parameters.arch }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/$(BUILD_BRANCH)'
      path: $(Build.ArtifactStagingDirectory)/download
      patterns: |
        libdashapi*.deb
    displayName: "Download sonic-dash-api"

  - script: |
      set -ex
      sudo dpkg -i $(find ./download -name *.deb)
      rm -rf download || true
    workingDirectory: $(Build.ArtifactStagingDirectory)
    displayName: "Install libnl3, libyang, sonic swss common, and sairedis"
  - script: |
      set -ex
      rm ../*.deb || true
      ./autogen.sh
      dpkg-buildpackage -us -uc -b -j$(nproc)
      mv ../*.deb $(Build.ArtifactStagingDirectory)
    displayName: "Compile sonic swss"
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive swss debian packages"
